{{- if .Values.gateway.enabled }}
{{- $gateway:= .Values.gateway }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "influxdb.fullname" . }}
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.gateway.annotations | indent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: {{ $gateway.name | default "gateway-ingress" }}
      namespace: {{ $gateway.namespace | default "istio-system" }} 
      sectionName: {{ $gateway.sectionName | default "https" }}
  hostnames:
    - "{{ $gateway.url }}"
  rules:
    - backendRefs: 
        - name: {{ .Values.name }}
          namespace: {{ .Values.namespace }}
          port: {{ .Values.service.port }}
          weight: {{ $gateway.weight | default 100 }}
{{- end }}