{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "influxdb.fullname" . }}
  labels:
  {{ include "influxdb.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "influxdb.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "influxdb.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
