{{- if .Values.rbac.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "influxdb.fullname" . }}
  labels:
  {{ include "influxdb.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
  {{- if .Values.psp.create }}
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames:
      - {{ template "influxdb.fullname" . }}
  {{- end }}
{{- end }}
