apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
  name: {{ template "influxdb.fullname" . }}-auth
data:
  {{- if .Values.adminUser.token }}
  admin-token: {{ .Values.adminUser.token  | b64enc | quote }}
  {{- else }}
  admin-token: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}

  {{- if .Values.adminUser.password }}
  admin-password: {{ .Values.adminUser.password | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
