apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
  name: {{ template "influxdb.fullname" . }}-auth
data:
  admin-password: {{ randAlphaNum 32 | b64enc | quote }}
  admin-token: {{ randAlphaNum 32 | b64enc | quote }}
