# apiVersion: v1
# kind: Secret
# metadata:
#   name: influxdb-license
# stringData:
#   json: YOUR JSON KEY
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
stringData:
  username: admin
  password: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-shared-secret
stringData:
  secret: MY RANDOM STRING
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: influxdb-tls
# type: kubernetes.io/tls
# stringData:
#   tls.crt: |
#     SOME CERTIFICATE
#   tls.key: |
#     SOME KEY
---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: influxdb-ddl-dml
# data:
#   ddl: |
#     CREATE DATABASE original
#     CREATE RETENTION POLICY oneday ON original DURATION 1d REPLICATION 1
#   dml: ""
