apiVersion: v1
kind: Secret
metadata:
  name: license
stringData:
  json: FAKE LICENSE KEY
---
apiVersion: v1
kind: Secret
metadata:
  name: auth
stringData:
  username: admin
  password: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: shared-secret
stringData:
  secret: MY RANDOM STRING
