apiVersion: v1
kind: Secret
metadata:
  name: license
data:
  json: FAKE LICENSE KEY
---
apiVersion: v1
kind: Secret
metadata:
  name: auth
data:
  # admin / admin
  username: YWRtaW4=
  password: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: shared-secret
data:
  secret: MY RANDOM STRING
