# Default values for influxdb-enterprise.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

# License-key and license-path are mutually exclusive. Use only one and leave the other blank.
license:
  # You can put your license key here for testing this chart out,
  # but we STRONGLY recommend using a license file stored in a secret
  # when you ship to production.
  # key: ""
  # secret:
  #   name: license
  #   key: json

# A secret with keys "username" and "password" is required
# This bootstrap configuration allows you to configure
# some parts of the InfluxDB system at install time.
#
# This job ONLY runs once, after the first `helm upgrade --install`
# or `helm install`
#
# This job WILL NOT run on upgrades
#
bootstrap:
  # This section allows you to enable authentication'
  # of the data nodes, which will create a username
  # and password for your "admin" account.
  # A secret should be provided, which will have the keys
  # "username" and "password" available.
  auth:
    secretName: auth
  # This section allows you to use DDL and DML to define
  # databases, retention policies, and inject some data.
  # When using the configMap setting, the keys "ddl" and "dml"
  # must exist, even if one of them is empty.
  # DDL is executed before DML, to enforce databases and retention policies
  # to exist.
  ddldml: {}
    # configMap: ddl-dml
    # resources: {}

meta:
  replicas: 1
  image: {}
    # override: true
    # pullPolicy: IfNotPresent
    # repository: influxdb
    # tag: "meta"
  # nodeSelector: {}
  # tolerations: []
  # affinity: {}
  # podAnnotations: {}
  # podSecurityContext: {}
  #   fsGroup: 2000
  # securityContext: {}
  #  capabilities:
  #    drop:
  #    - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  #
  #
  # This secret needs a key called "secret" and it should be a long random string
  # Please see docs for shared-internal-secret:
  # https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/config-data-nodes/#meta-internal-shared-secret
  sharedSecret:
    secretName: shared-secret
  #
  ## Persist data to a persistent volume
  ##
  persistence:
    enabled: false
    ## A manually managed Persistent Volume and Claim
    ## Requires persistence.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    # existingClaim:
    ## influxdb data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    # annotations:
    # accessMode: ReadWriteOnce
    # size: 8Gi
  # Pick one
  podDisruptionBudget:
    # maxUnavailable: 2
    minAvailable: 2
  https:
    # If you need to debug the data nodes registration with the meta nodes, we recommend
    # that you comment out the active curl command in the data-configmap and uncomment the following
    # line, which has -v / debugging enabled.
    enabled: true
    # The `useCertManager` option, when set to true, will
    # automatically create the certificate resources for you.
    # You do not need to set the secret.name when using this flag.
    useCertManager: true
    secret:
      name: tls-secret
      # crt: tls.crt
      # key: tls.key
    insecure: true


data:
  replicas: 1
  image: {}
    # override: true
    # pullPolicy: IfNotPresent
    # repository: influxdb
    # tag: "data"
  # nodeSelector: {}
  # tolerations: []
  # affinity: {}
  # podAnnotations: {}
  # podSecurityContext: {}
  #   fsGroup: 2000
  # securityContext: {}
  #  capabilities:
  #    drop:
  #    - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  ## Persist data to a persistent volume
  ##
  persistence:
    enabled: false
    ## A manually managed Persistent Volume and Claim
    ## Requires persistence.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    # existingClaim:
    ## influxdb data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    # annotations:
    # accessMode: ReadWriteOnce
    # size: 8Gi
  https:
    # If you need to debug the data nodes registration with the meta nodes, we recommend
    # that you comment out the active curl command in the data-configmap and uncomment the following
    # line, which has -v / debugging enabled.
    enabled: true
    # The `useCertManager` option, when set to true, will
    # automatically create the certificate resources for you.
    # You do not need to set the secret.name when using this flag.
    useCertManager: true
    secret:
      name: tls-secret
      # crt: tls.crt
      # key: tls.key
    insecure: true
