{{- if and .Values.rbac.create (not .Values.rbac.namespaced) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kapacitor.fullname" . }}-clusterrolebinding
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app: {{ template "kapacitor.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kapacitor.serviceAccountName" . }}
    namespace: {{ template "kapacitor.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "kapacitor.fullname" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
