override_config:
  toml: |+
    [global_tags]
    config = "toml"

    [agent]
    collection_jitter = "0s"
    debug = false
    flush_interval = "10s"
    flush_jitter = "0s"
    hostname = "$HOSTNAME"
    interval = "10s"
    logfile = ""
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    omit_hostname = false
    precision = ""
    quiet = false
    round_interval = true

    [[outputs.influxdb]]
    database = "telegraf"
    urls = ["http://influxdb.monitoring.svc:8086"]

    [[inputs.statsd]]
    allowed_pending_messages = 10000
    metric_separator = "_"
    percentile_limit = 1000
    percentiles = [50.0, 90.0, 99.0, 99.9, 99.95, 100.0]
    service_address = ":8125"

