## Image Settings
##
image:
  repository: "chronograf"
  ## DockerHub is now the preferred repo
  ## alternative: quay.io/influxdb/chronograf
  tag: 1.9.4
  pullPolicy: IfNotPresent

## Specify a service type
## ClusterIP is default
## ref: http://kubernetes.io/docs/user-guide/services/
##
service:
  replicas: 1
  type: ClusterIP

## Persist data to a persistent volume
##
persistence:
  enabled: false
  ## chronograf data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  # storageClass: "-"
  ## If keepPvc is true, pvc will not be deleted after running helm uninstall
  # keepPvc:
  accessMode: ReadWriteOnce
  size: 8Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 2Gi
    cpu: 2

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
#
nodeSelector: {}

 ## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

 ## Affinity for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Customize probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
##
startupProbe:
  enabled: true

## Configure the ingress object to hook into existing infastructure
## ref : http://kubernetes.io/docs/user-guide/ingress/
## OPTIONALLY you can set .Values.ingress.secretName to set which secret to use
##
ingress:
  enabled: false
  tls: false
  hostname: chronograf.foobar.com
  className: null
  annotations: {}
    # kubernetes.io/ingress.class: "nginx"
    # secretName: my-tls-cert
    # kubernetes.io/tls-acme: "true"
  path: /

## OAuth Settings for OAuth Providers
## More information -> https://github.com/influxdata/chronograf/blob/master/docs/auth.md
##
oauth:
  # Need to set to true to use any of the oauth options
  enabled: false
  # Used for JWT to support running multiple copies of Chronograf
  # token_secret: CHANGE_ME
  # Set if the OAuth provider implements oidc with RS256 signature
  # use_id_token: true
  # jwks_url: ""
  github:
    enabled: false
    # client_id: CHANGE_ME
    # client_secret: CHANGE_ME
    # This is a comma separated list of GH organizations (OPTIONAL)
    gh_orgs: ""
  google:
    enabled: false
    # client_id: CHANGE_ME
    # client_secret: CHANGE_ME
    # eg. http://chronograf.foobar.com
    public_url: ""
    # This is a comma separated list of Google Apps domains (OPTIONAL)
    domains: ""
  heroku:
    enabled: false
    # client_id: CHANGE_ME
    # client_secret: CHANGE_ME
    # This is a comma separated list of Heroku organizations (OPTIONAL)
    he_orgs: ""
  generic:
    enabled: false
    # client_id: CHANGE_ME
    # client_secret: CHANGE_ME
    api_key: ""
    scopes: ""
    # eg. http://chronograf.foobar.com
    public_url: ""
    auth_url: ""
    token_url: ""
    api_url: ""
    # optional
    # name: "generic"
    # domains: ""

## Extra environment variables that will be passed onto deployment pods
env:
  HOST_PAGE_DISABLED: true

## The name of a secret in the same kubernetes namespace which contain values to be added to the environment
## This can be useful for auth tokens, etc
envFromSecret: ""

# volumes:
# - name: chronograf-output-influxdb2
#   configMap:
#     name: "chronograf-output-influxdb2"
# mountPoints:
# - name: chronograf-output-influxdb2
#   mountPath: /var/lib/chronograf/conf.d
#   subPath: influxdb2.conf

## Use Recreate when persistence is enabled
updateStrategy:
  type: RollingUpdate

influxdb: {}
  ## Name of an existing Secrect used to set the environment variables for the
  ## InfluxDB user and password. The expected keys in the secret are
  ## `influxdb-user` and `influxdb-password`.
  ##
  # existingSecret: influxdb-auth
