{{- if .Values.certManager.enable -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "telegraf-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "telegraf-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - "{{ include "telegraf-operator.fullname" . }}.{{ .Release.Namespace }}.svc"
  - "{{ include "telegraf-operator.fullname" . }}.{{ .Release.Namespace }}"
  isCA: true
  issuerRef:
    kind: Issuer
    name: telegraf-operator-issuer
  secretName: telegraf-operator-tls
{{- end -}}
