apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "telegraf-operator.labels" . | nindent 4 }}
  name: {{ include "telegraf-operator.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs: ["get", "list"]
- apiGroups:
  - ""
  resources:
  - pods
  verbs: ["get"]
