{{- if .Values.certManager.certificate.enable -}}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: selfsigned
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "telegraf-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end -}}
