{{- if .Values.classes.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.classes.secretName }}
  namespace: {{ .Release.Namespace }}
stringData: {{ .Values.classes.data | toYaml | nindent 2 }}
{{- end }}
---
{{- if eq .Values.certManager.enable false -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: telegraf-operator-tls
  labels:
    {{- include "telegraf-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "telegraf-operator.gen-certs" . ) | indent 2 }}
{{- end }}
