{{- if .Values.classes.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.classes.secretName }}
  namespace: {{ .Release.Namespace }}
stringData: {{ .Values.classes.data | toYaml | nindent 2 }}
{{- end }}
