apiVersion: v1
kind: Service
metadata:
  name: {{ include "telegraf-operator.fullname" . }}
  labels:
    {{- include "telegraf-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: https
  selector:
    {{- include "telegraf-operator.selectorLabels" . | nindent 4 }}
