apiVersion: v1
kind: Service
metadata:
  name: {{ template "influxdb-enterprise.fullname" . }}-data
  labels:
    influxdb.influxdata.com/component: data
    {{- include "influxdb-enterprise.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 8086
    protocol: TCP
    name: http
  - port: 8088
    protocol: TCP
    name: rpc
  - port: 8089
    protocol: UDP
    name: udp
  - port: 2003
    # Graphite supports TCP and UDP,
    # so this should __maybe__ be configurable
    # Though most use TCP
    protocol: TCP
    name: graphite
  - port: 4242
    protocol: TCP
    name: opentsdb
  - port: 25826
    protocol: UDP
    name: collectd
  selector:
    influxdb.influxdata.com/component: data
    {{- include "influxdb-enterprise.selectorLabels" . | nindent 4 }}
