apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "influxdb-enterprise.fullname" . }}-meta
  labels:
    app.kubernetes.io/component: meta
    {{- include "influxdb-enterprise.labels" . | nindent 4 }}
data:
  influxdb-meta.conf: |+
    bind-address = ":8091"
    reporting-disabled = false

    [enterprise]
      {{ if .Values.license.key }}
      # license-key and license-path are mutually exclusive, use only one and leave the other blank
      license-key = "{{ .Values.license.key }}" #✨ mutually exclusive with license-path
      {{ else }}
      # license-key and license-path are mutually exclusive, use only one and leave the other blank
      license-path = "/etc/influxdb/license.json"
      {{ end }}

    [meta]
      dir = "/var/lib/influxdb/meta"

  entrypoint.sh: |+
    #!/usr/bin/env sh
    set -e
    META_LEADER=$(hostname -f | sed -r 's/-[0-9]+./-0./')
    if [ $META_LEADER != $(hostname -f) ]; then
      influxd-ctl join ${META_LEADER}:8091
    else
      influxd-ctl add-meta $(hostname -f):8091
    fi
