
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "influxdb-enterprise.fullname" . }}-meta-pdb
  labels:
    {{- include "influxdb-enterprise.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      influxdb.influxdata.com/component: meta
      {{- include "influxdb-enterprise.selectorLabels" . | nindent 4 }}
{{ toYaml .Values.meta.podDisruptionBudget | indent 2 }}
