license:
  existingSecret: influxdb3-license

objectStorage:
  type: file
  file:
    persistence:
      accessMode: ReadWriteOnce
      size: 5Gi

ingress:
  enabled: false

ingester:
  replicas: 1
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "2000m"
      memory: "4Gi"
  persistence:
    enabled: false

querier:
  replicas: 1
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "2000m"
      memory: "4Gi"

compactor:
  replicas: 1
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "2000m"
      memory: "4Gi"

processingEngine:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "2000m"
      memory: "4Gi"
  persistence:
    enabled: false

security:
  auth:
    adminToken:
      existingSecret: influxdb3-bootstrap-tokens
    permissionTokens:
      existingSecret: influxdb3-bootstrap-tokens
