{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "influxdb.fullname" . }}
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations:
  {{ toYaml .Values.ingress.annotations | indent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ .Values.ingress.secretName }}
{{- end }}
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
  rules:
  {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname }}
      http:
  {{- else }}
    - http:
  {{- end }}
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "influxdb.fullname" . }}
                port:
                  number: {{ include "influxdb.httpPortNumber" . }}
  {{- end }}
