apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  name: {{ include "influxdb.fullname" . }}
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: api
    port: {{ .Values.config.http.bind_address | default 8086 }}
    targetPort: api
    {{- if (and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.http))) }}
    nodePort: {{ .Values.service.nodePorts.http | int }}
    {{- end }}
  - name: rpc
    port: {{ .Values.config.rpc.bind_address | default 8088 }}
    targetPort: rpc
  {{- if .Values.config.graphite.enabled }}
  - name: graphite
    port: {{ .Values.config.graphite.bind_address | default 2003 }}
    targetPort: graphite
  {{- end }}
  {{- if .Values.config.collectd.enabled }}
  - name: collectd
    port: {{ .Values.config.collectd.bind_address | default 25826 }}
    protocol: UDP
    targetPort: collectd
  {{- end }}
  {{- if .Values.config.udp.enabled }}
  - name: udp
    port: {{ .Values.config.udp.bind_address | default 8089 }}
    protocol: UDP
    targetPort: udp
  {{- end }}
  {{- if .Values.config.opentsdb.enabled }}
  - name: opentsdb
    port: {{ .Values.config.opentsdb.bind_address | default 4242 }}
    targetPort: opentsdb
  {{- end }}
  selector:
    {{- include "influxdb.selectorLabels" . | nindent 4 }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
