{{- $type := .Values.objectStorage.type }}
{{- if and (eq $type "s3") (not .Values.objectStorage.s3.existingSecret) .Values.objectStorage.s3.accessKeyId }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "influxdb3-core.objectStorageSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "influxdb3-core.labels" . | nindent 4 }}
type: Opaque
data:
  access-key-id: {{ .Values.objectStorage.s3.accessKeyId | b64enc | quote }}
  secret-access-key: {{ .Values.objectStorage.s3.secretAccessKey | b64enc | quote }}
  {{- if .Values.objectStorage.s3.sessionToken }}
  session-token: {{ .Values.objectStorage.s3.sessionToken | b64enc | quote }}
  {{- end }}
{{- else if and (eq $type "google") (not .Values.objectStorage.google.existingSecret) .Values.objectStorage.google.serviceAccountJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "influxdb3-core.objectStorageSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "influxdb3-core.labels" . | nindent 4 }}
type: Opaque
data:
  service-account.json: {{ .Values.objectStorage.google.serviceAccountJson | b64enc | quote }}
{{- else if and (eq $type "azure") (not .Values.objectStorage.azure.existingSecret) .Values.objectStorage.azure.storageAccount }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "influxdb3-core.objectStorageSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "influxdb3-core.labels" . | nindent 4 }}
type: Opaque
data:
  storage-account: {{ .Values.objectStorage.azure.storageAccount | b64enc | quote }}
  access-key: {{ .Values.objectStorage.azure.accessKey | b64enc | quote }}
{{- end }}
{{- if and (eq $type "s3") .Values.objectStorage.s3.credentialsFile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "influxdb3-core.fullname" . }}-aws-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "influxdb3-core.labels" . | nindent 4 }}
type: Opaque
data:
  credentials: {{ .Values.objectStorage.s3.credentialsFile | b64enc | quote }}
{{- end }}
