name: Release Helm Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        run: |
          curl -sSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm init --client-only

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-alpha.2
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
